-- AI News Aggregator Database Schema
-- Generated: 2025-08-22T13:56:55.107009
-- This represents the ACTUAL current state of the database

-- ============================================================
-- TABLES AND VIEWS
-- ============================================================

-- sources
-- Stores all content sources (websites and Twitter accounts)
-- Row count: 15
-- Type: TABLE
-- Columns:
--   id: uuid
--   name: text
--   url: text
--   active: boolean
--   created_at: timestamp
--   category: timestamp
--   source_type: text
--   twitter_username: unknown (nullable)

-- articles
-- Stores articles from website sources
-- Row count: 406
-- Type: TABLE
-- Columns:
--   id: uuid
--   source_id: text
--   headline: text
--   url: text
--   published_at: timestamp
--   scraped_at: timestamp
--   full_content: unknown (nullable)
--   is_ai_related: boolean
--   summary: unknown (nullable)
--   included_in_newsletter: boolean
--   view_count: integer
--   tags: array
--   image_url: unknown (nullable)
--   processing_stage: text
--   crawl_batch_id: unknown (nullable)
--   actual_published_date: unknown (nullable)
--   confidence: unknown (nullable)
--   error_message: unknown (nullable)
--   retry_count: integer
--   tweet_id: unknown (nullable)
--   author_username: unknown (nullable)
--   like_count: integer
--   retweet_count: integer
--   reply_count: integer

-- tweets
-- Stores tweets from Twitter/X sources
-- Row count: 2
-- Type: TABLE
-- Columns:
--   id: uuid
--   source_id: text
--   tweet_id: text
--   author_username: text
--   content: text
--   like_count: integer
--   retweet_count: integer
--   reply_count: integer
--   view_count: integer
--   bookmark_count: integer
--   is_reply: boolean
--   is_retweet: boolean
--   is_quote_tweet: boolean
--   has_media: boolean
--   media_urls: unknown (nullable)
--   hashtags: unknown (nullable)
--   mentions: unknown (nullable)
--   urls: unknown (nullable)
--   conversation_id: unknown (nullable)
--   in_reply_to_tweet_id: unknown (nullable)
--   quoted_tweet_id: unknown (nullable)
--   thread_position: unknown (nullable)
--   quoted_tweet_content: unknown (nullable)
--   quoted_tweet_author: unknown (nullable)
--   is_ai_related: boolean
--   ai_summary: unknown (nullable)
--   ai_tags: array
--   ai_relevance_score: unknown (nullable)
--   ai_processed_at: unknown (nullable)
--   published_at: timestamp
--   fetched_at: timestamp
--   updated_at: timestamp
--   included_in_newsletter: boolean
--   newsletter_date: unknown (nullable)
--   display_priority: integer

-- source_stats
-- Tracks crawling statistics per source
-- Row count: 0
-- Type: TABLE
-- Columns:

-- unified_content
-- View combining articles and tweets
-- Row count: 406
-- Type: VIEW
-- Columns:
--   content_type: text
--   id: uuid
--   source_id: text
--   source_name: text
--   source_type: text
--   headline: text
--   url: text
--   content: unknown (nullable)
--   summary: unknown (nullable)
--   is_ai_related: boolean
--   tags: array
--   published_at: timestamp
--   fetched_at: timestamp
--   like_count: integer
--   retweet_count: integer
--   reply_count: integer
--   engagement_score: integer
--   view_count: integer
--   included_in_newsletter: boolean
--   image_url: unknown (nullable)
--   author_username: unknown (nullable)
--   tweet_id: unknown (nullable)

-- article_processing_status
-- View for monitoring article processing pipeline
-- Row count: 7
-- Type: VIEW
-- Columns:
--   processing_stage: text
--   count: integer
--   crawl_date: timestamp

-- daily_twitter_stats
-- Materialized view for Twitter statistics
-- Row count: 2
-- Type: VIEW
-- Columns:
--   date: timestamp
--   source_name: text
--   twitter_username: text
--   tweet_count: integer
--   ai_tweet_count: integer
--   avg_likes: float
--   avg_retweets: float
--   max_likes: integer
--   max_retweets: integer
--   total_engagement: integer
