services:
  - type: web
    name: ai-news-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: PORT
        value: 8000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: FIRECRAWL_API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true