name: AI News Crawler
on:
  workflow_dispatch:
  schedule:
    # Run daily at 9 AM UTC (adjust for your timezone)
    - cron: '0 9 * * *'
jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt
      
      - name: Debug - Check files
        run: |
          echo "Current directory:"
          pwd
          echo "Backend directory contents:"
          ls -la backend/
          echo "Workers directory:"
          ls -la backend/src/workers/
          echo "Python version:"
          python --version
      
      - name: Run crawler
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          FIRECRAWL_API_KEY: ${{ secrets.FIRECRAWL_API_KEY }}
        run: |
          cd backend
          echo "Running crawler from: $(pwd)"
          python src/workers/news_crawler_v3.py --once