name: AI News Crawler

  on:
    schedule:
      # Run every 30 minutes
      - cron: '*/30 * * * *'
    workflow_dispatch: # Allow manual trigger

  jobs:
    crawl:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

       - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt || (
            grep -v firecrawl-py requirements.txt > temp_requirements.txt
            pip install -r temp_requirements.txt
            pip install git+https://github.com/mendableai/firecrawl-py.git
          )



      - name: Run crawler
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          FIRECRAWL_API_KEY: ${{ secrets.FIRECRAWL_API_KEY }}
        run: |
          cd backend
          python -m src.workers.news_crawler --once

      - name: Log completion
        run: echo "Crawler run completed at $(date)"

